build:
  performance:
    jobs:
      run-grakn:
        machine: grabl-ubuntu-1910-cache-run-grakn
        type: background
        timeout: "18000"
        script: |
          echo "hello run-grakn"
      test-performance-big:
        machine: grabl-ubuntu-1910-cache-test-performance-big
        type: foreground
        timeout: "18000"
        script: |
          echo "test-performance-big"
          sleep 5h
    execution:
      - run-grakn
      - test-performance-big:
          depends: [run-grakn]

